[tool.poetry]
name = "broken_zip"
version = "0.1.0"
description = "A script to create a broken zip file"
authors = ["Björn Guth <b.guth@netcon-consulting.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
